### ISSUE TITLE
Watch Multiple Games at Once

### ISSUE THREAD

**Issue by alecgorge** [Alexqw/xbmc-gamepass#172]
Do you think some special handling can be done with the JSESSIONID in pigskin.py to enable multiple concurrent streams? [This reddit thread](https://www.reddit.com/r/GreenBayPackers/comments/1qt1yp/how_to_use_nfl_game_pass_without_vpn_if_someone/) seems to show that session hijacking is effective at allowing multiple people to use one account simultaneously.

I think this could be applied to service multiple streams. I'm not familiar with the codebase so I thought I might bring it to your attention until I have time to get more familiar and test out my theory in the next couple weeks.

**Comment by kaileu** [comment]
There is a even simpler workaround to watch everything completetly free BUT this kind of hacks has legal issues so i doubt we aren't allowed to implement this kind of things for public usage ;-)

Mit freundlichen Grüßen
KaiLeu

**Comment by alecgorge** [comment]
The official Game Pass app lets me stream 4 games at once and all I want to do is replicate that but I certainly understand.

**Comment by Alexqw** [comment]
@alecgorge Multiple streams is definitely doable, but the question is how you want to use them. 1) On multiple devices behind the same router? 2) Or multiple streams on one device?

What @kaileu referred to is multiple streams for different people with different IPs. And I agree with him, that (as far as I am aware) that is against the NFL's TOS. Thankfully I don't think that's what you're asking for.

I /think/ that 1) already works (multiple streams to different devices behind the router). Last time I worked heavily with the streams (which was 1-2 years ago), GamePass appeared to authorize the IP to play streams, which made it much easier for me to test on both my laptop and my TV.

2) will be more difficult just because an interface will have to be built. And I imagine it'll be pretty taxing on the hardware to decode 4 encrypted streams simultaneously and display them. I think it's certainly doable, but the majority of work will be getting Kodi to do want you want it to do. It's used to only playing one media file at a time. It might take some creativity (composing a new, interim stream) to get it to handle multiples. But that's all a guess.

**Comment by Alexqw** [comment]
@alecgorge I was thinking about this a bit more, and it /might/ be easier on the Kodi side than I anticipated. I would recommend taking a look at the Coaches Film skin we ship and seeing if you can use the same approach, just for 4 different streams.

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw This approach will not work for less powerful devices like the rpi, since they can't even handle the coaches show gui!

**Comment by Alexqw** [comment]
@BaumSchorle Yeah, but I'm ok with that. If someone wants to take the time to add the feature properly, then I don't think low-performance devices should be a blocker. I think RPi users know that it's a tiny machine that can do most but not all tasks. And they'll only be missing out on that one feature, not the entire addon.

---Alex

**Comment by frostyon420** [comment]
damn i wish i still had access to GP. last year was sweet. as was the year b4 last. I hope i can figure something out soon. 
@kaileu you cant just tell us that bit of info and not expect someone to ask about it. If you dont want to post it publicly i understand, but what a tease lol.

**Comment by kaileu** [comment]
I can give you a hint where to find a solution :-P 
1.
The Apps has the functionality to watch the streams without a login.
Why not using it.

2.
The Streams has the same construction everytime the only thing that changes are the Server! So build your own Link by Hand and check on which Server the stream is running.
You only need a cookie to Livestreaming but this didn't change over years. So 1 Cookie per Stream and your done ;-).

So that was enough Hints ;-) . All Information where ONLY for theoretic research.

Mit freundlichen Grüßen
KaiLeu

**Comment by Alexqw** [comment]
Sorry to be the curmudgeon, but please don't have these conversions here. Nothing explicit, nothing implicit, no hints, just not here. It's not so much that I care, it's that lawyers care. And I don't want any lawyer thinking that this addon has /anything/ to with anything other than the 100% legitimate use of streams in compliance with the NFL's TOS.

I'm not angry or anything; I'm just trying to make sure this addon doesn't induce the ire of the NFL.

I'm deleting three posts in this thread for CYA purposes (even though it was mostly just hinting).

The resident ass-hole, ;-)
---Alex

**Comment by frostyon420** [comment]
my bad man. Not trying to get anyone in trouble.

**Comment by Alexqw** [comment]
@frostyon420 No worries. I know you meant no harm. :-)

**Comment by Alexqw** [comment]
@alecgorge Any movement on this? It'd be cool to support this for those who like the ADHD experience. ;-)

---Alex

**Comment by alecgorge** [comment]
I'm a big user of Plex, so I mostly use [NFL.bundle](https://github.com/alecgorge/NFL.bundle), but much of is (probably) the same.

In addition to Plex, I also run this small server called [hls-decryptor](https://github.com/alecgorge/hls-decryptor). It is a small node.js server that intercepts the HLS playlists and decrypts the segments. Since every request goes through this server, the requests module shares cookies between requests.

This also has the added benefit of allowing you to use AdFreeTime or something on the Plex server to let all the Plex clients use NFL GamePass international by only changing the DNS settings on the server.

**Comment by Alexqw** [comment]
@alecgorge So, turns out I'm wrong. Multipl video playback is a [known limitation](http://forum.kodi.tv/showthread.php?tid=241654&pid=2129065#pid2129065) of DVDPlayer in Kodi.

There is an effort to [overhaul/replace DVDPlayer](http://forum.kodi.tv/forumdisplay.php?fid=240), but there's no telling when that'll be finished/merged.

Closing, until Kodi can even support this.

---Alex
