### ISSUE TITLE
Games won't play on mac

### ISSUE THREAD

**Issue by chovy** [Alexqw/xbmc-gamepass#181]
http://xbmclogs.com/piqkofbea

video: https://www.dropbox.com/s/y5awopiis7ar2r5/xmbc-gamepass-bug-1.m4v?dl=0

It gets the quality listing, but doesn't play.

**Comment by BaumSchorle** [comment]
The logs do not show any error, the video you selected gets handed to Kodi to play, but then nothing happens.

I still think this is an issue with your DNS/Proxy approach, you are using. Since you are in the US and using the international version of GamePass.
You may want to check, but we can not support you on this.

I am sitting in Europe and everything works fine, with the older version in repo and the latest version.

**Comment by chovy** [comment]
I can't login without using DNS from adfreetime. And it works fine on my FireTV.

**Comment by BaumSchorle** [comment]
I double checked the logs and I can't find anything that goes wrong in our addon. It starts the stream as it does on my installation.

Maybe this really is an issue with your Kodi installation.

**Comment by Alexqw** [comment]
It's worth noting that GamePass is having a lot of growing pains ATM. https://twitter.com/NFLGamePass/with_replies

I'm not saying that this addon isn't at fault, but we should try to keep it in mind so we aren't chasing dead-ends.

**Comment by Alexqw** [comment]
Closing, as it looks like a corrupt install of Kodi. @chovy If you are still having this problem and think it's a bug in this addon, please feel free to reopen. But also make sure to check that it's not bug #183, which I'm still working on.

---Alex
