### ISSUE TITLE
Unable to select Championship Round - Some bad jujumagumbo just went down

### ISSUE THREAD

**Issue by Penryn123** [Alexqw/xbmc-gamepass#229]
Hi All, Error (Some bad jujumagumbo just went down) Occurs when clicking in Divisional Championship. Im using a international Gamepass from within Germany. Games yesterday worked perfectly. 
Version 0.90 was not downloadable from the resp. Using a Fire TV with Kodi 15.2. Error is reproducable.

Debuglog: http://xbmclogs.com/p5fmguk71

Thanks for help and the Great work with your addon! Need to watch the games on Sunday :P

**Comment by kaileu** [comment]
the reason is a missing condition which check if there is a game or not.
The Championship games aren't available at the Moments so this error occurs.

Das Problem ist, dass eine Abfrage fehlt ob die antwort die der Gamepass Server liefert leer ist oder nicht. Dies entsteht dadurch, dass die Spiele zurzeit noch nicht offiziell eingetragen sind dementsprechend liefert der Server kein Ergebnis und die Fehlermeldung popt auf.

**Comment by Penryn123** [comment]
Thank you for the quick reply to my issue. if i understand correclty, the issue will "solve iteself" by sunday?

Danke für die schnelle Antwort zu meinem Problem. Somit sollte sich das Problem also bis Sonntag "von selbst lösen" wenn ich das richtig verstanden habe?

**Comment by kaileu** [comment]
Ja genau.

**Comment by Penryn123** [comment]
Besten Dank, Woche gerettet!
Thank You, you saved the Week!
