### ISSUE TITLE
Feature Request: dynamic Shows

### ISSUE THREAD

**Issue by kaileu** [Alexqw/xbmc-gamepass#231]
Cause i am having Problems with the iterations of the dictionary..... i will post it at a official feauture request.

At the moment the nfl shows are static and this isn't a good solution.
A better solution would be to parse the elements from simpleconsole.

**Comment by Alexqw** [comment]
@kaileu I agree, that it'd be better to parse the list that GamePass sends us. I can't remember why we chose to do it this way, but I don't see a good reason anymore.

However, it would be a good idea if we maintained a blacklist (or at least a greylist), where we don't display (or display with a warning) shows which are known to not work. There are a few, unfortunately. :-/

---Alex

**Comment by BaumSchorle** [comment]
I am currently working on this, it's not that complicated but a little tricky, which could result in problems as soon as they change anything.

One problem is, that they name their 'Games seasons' and 'NFL-Network seasons' differently, one they call just 2016 the other is called 'Season 2016'  and to make it more complicated they have a speciality with the Superbowl Archive, they have a season called 'Archive' there.

My idea is to read the NFL-Network seasons dynamically which would result in a longer text on the guy, hopefully this doesnt break anything. I don't want to mess around with the name of the seasons, who knows what they think of next.

The upsight on this approach is, that we read everything dynamically and we don't have to maintain anything if they add new shows or seasons.

**Comment by kaileu** [comment]
Yes i think this is a good solution.

**Comment by Alexqw** [comment]
@BaumSchorle Great that you're working on this. Your approach sounds good to me. The key features, IMO, are:

1. That it works ;-)
2. That the parsing is robust enough that it requires less maintenance than our hand-maintained version. (Of course we can't anticipate everything, but you get my point)
3. That we can grey-list (warn users) about certain show/year combos that we /know/ don't work (as there are still a few).

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw Since the weather is gonna be bad today, I will have plenty of time to get this to work. ;-)

To your point 3: I hope that we don't have to grey-list cause all the shows provided on android devices should also work on our addon

**Comment by Alexqw** [comment]
@BaumSchorle Haha. Nice; may it storm like hell. ;-)

Re-point 3. That'd be /great/ if everything returned just worked.

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw I  just commited the code to master which parses the shows dynamically. I had to do more tweaking than I wanted, but my Idea with just taking the season names as is, wasn't good because they are too long for the guy.

Please test this properly, most of the shows I tested were working. However we may have to do some black-listing, since some Total Access shows of 2011 are not working.
I checked with the Android app and you only get 2014 and 2015 season on Android.

**Comment by Alexqw** [comment]
@BaumSchorle Nice. The season name normalizing makes sense.

With regard to the blacklisting for the shows, do you think the android app is doing blacklisting? Or is there some way to determine whether a show is playable or not...

---Alex

**Comment by Alexqw** [comment]
Ahh, sorry. I also meant to add that I'll test this sometime this weekend. I don't have access to my dev box ATM.

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw I need to dig a little bit deeper, but I think Android app is blacklisting, since the request returns Total Access from 2016-1010 but only 2016-2014 is working.
All other shows are working perfectly.

**Comment by Alexqw** [comment]
@BaumSchorle I did a bit a cleanup but didn't go digging through the simpleconsole results or anything. I did some quick testing and everything looks good (except those Total Access years).

So, I have two ideas,

1. Build a black list and check against that list and kick out any matches (in default.py, because it's not pigskin's fault that kodi can't play those streams).

2. Just accept that we'll probably always be playing a bit of whack'a'mole with these shows, so to hell with maintaining a list, and just wrap all show playing with a try statement that results in a more specific error message. Something saying that some shows are known to not work, please test against official app, if you think there's a problem, open a bug (granted, that's a really long error message, but you get my point).

Other than that, this is pretty much done. Well done. :-)

Thoughts?

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw good, I am not that good of a coder; I am more of a Sys- and DB-Admin ;-)

I think both are viable options, but option two is probably easier to setup and needs no maintenance in the futuer.
So I would go this way.

**Comment by Alexqw** [comment]
@BaumSchorle As am I (a Sys- and Storage-admin), so we make a good, forgiving pair. ;-)

I tend to agree that option two feels more practical.

---Alex

**Comment by Alexqw** [comment]
This seems to be working, and I added an error message specifically for show playback problems. This should be good to go.

@BaumSchorle Thanks for doing the heavy lifting on this.

---Alex
