### ISSUE TITLE
Stottern aller Videos

### ISSUE THREAD

**Issue by whitesnuf** [Alexqw/xbmc-gamepass#245]
Hallo,

seit dem heutigen App-Update stottern bei mir in Kodi auf drei Plattformen die Streams.

Könnt ihr da mal reinschauen?

Grüße, Whitesnuf

**Comment by kaileu** [comment]
Hast du die Qualität mal runtergeschraubt?
Kann gut sein dass die Streams einfach überlastet sind.
Falls das problem immer noch auftritt solltest du ein Debug log posten.
Bei mir läuft alles flüssig.

Mit freundlichen Grüßen
Kai Leutner

**Comment by whitesnuf** [comment]
Habs eben mit geringerer Qualität versucht und die Streams stottern trotzdem.

Das Log habe ich angehängt.

Grüße, Ralf

[kodi.log.zip](https://github.com/Alexqw/xbmc-gamepass/files/404526/kodi.log.zip)

**Comment by kaileu** [comment]
@Alexqw what do you think?
For me it looks like a problem from ffmpeg many errors like

ffmpeg[D8B7F930]: [NULL] Current profile doesn't provide more RBSP  
data in PPS, skipping
22:04:25 T:18446744073050519856   ERROR: ffmpeg[D8B7F930]: Invalid UE  
golomb code
22:04:25 T:18446744073033488688

Any Idea why this is cause a stuttering while playback?
The quality seems not the problem to be because even with 800 the  
problem occours?

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment]
@kaileu Very odd indeed. I've found a few bug reports and patches for such ffmpeg errors, but it's odd that none of the rest of us are see these problems.

If I had to guess, @whitesnuf is running a custom ARM distro and they're encountering a bug in their build. That or the CPU is pegged for some other reason and is starved.

In all, @whitesnuf I'm happy to provide a few ideas (above), but I'm pretty certain that the addon is not at fault here.

Closing, but please reopen with a debug log if you have new reason to believe it's a problem with the addon.

---Alex

**Comment by whitesnuf** [comment]
I have found the error. It was a Beta Firmware for my Router. Reverted to the official Firmware and everything works smooth.
Thanks for investigation.

**Comment by Alexqw** [comment]
@whitesnuf Glad to hear. :-)
