### ISSUE TITLE
Not able to Login in Version 0.9.2

### ISSUE THREAD

**Issue by Displayel** [Alexqw/xbmc-gamepass#266]
Hi guys,

i updated to version 0.9.2 on Kodi 16.1 and it didn´t work got an error saying can´t login check if you have a valid subscription, when i went back to 0.9.1 there were no issues and i could login again. 
i´m using a nvidia shield, here is my dilema now , i though i might upgrade to Krypton Beta 1 and the error was still there, but now i can´t downgrade again to 0.9.1 because i get an error message when trying to load the old zip file.

i´m not sure if i have debug enabled in the gamepass because i couldn´t get in but i did the log 

here is the adress , this is the one were i tried to login but couldn´t
http://paste.ubuntu.com/23094339/

this is the one where i tried to downgrade back to 0.9.1 but the error showed up
http://paste.ubuntu.com/23094366/

hope you can help

Cheers Alex

**Comment by Alexqw** [comment]
@Displayel Could you please enable debugging in both Kodi and the addon, and then provide that log? The logs you posted don't provide enough information.

Also, assuming you're the one who recently emailed me (and you're installing by hand rather than via Kodi's repo), did you read the README as I suggested and install the two new dependencies introduced with 0.9.2?

---Alex

**Comment by Displayel** [comment]
i did install the scriptmodule 0.2.10 from 24th of august, which is the 2nd one ?

unfortunately i cant enable debugging in the addon because i cant get in

**Comment by Ghoschdi** [comment]
@Displayel: Just hold your enter key (keyboard or remote) long while over the GP addon. This opens the drop down, go to settings and enable debug there. Otherwise you can always go to Kodi's addon management (where you install addons) and select GP addon via "my addons" -> "video addons". This will bring up a screen on which you can select configure.

And if you installed m3u8 version 0.2.10 manually you also need to install the dependency iso8601 from here: http://mirrors.kodi.tv/addons/helix/script.module.iso8601/...

Owning an NVIDIA Shield TV myself, i can only recommend you install Kodi via official play store and install Kodi addons via repo or the integrated zip install function. Everything else is just double efforts and a lot of bug hunting...

**Comment by Alexqw** [comment]
@Displayel It seems that you have had difficulty, twice, finding the appropriate links/information for dependencies in the [README](https://github.com/Alexqw/xbmc-gamepass#any-dependencies). Do you have a suggestion for how the information can be presented more clearly?

---Alex

**Comment by Displayel** [comment]
so i did a clean install of 16.1 and then upgraded to 17 B1 because i read that it is much more stable now and installed the addon via zip file and it worked, so no idea what was the hiccup before but seems its solved.
Thats what i could have done at first place before opening this issue but a clean install is a drag because the import of my mediathek is always a pain in the a** because it doesnt import all the settings the way it was before...so i apologize.

Alex thanks again for your quick support, its unreal how fast you reply even by mail and of course to all the others in here, appreciate it bigtime

**Comment by Alexqw** [comment]
@Displayel I'm glad to hear that the addon is working for you now.

Thanks @Ghoschdi for helping out. :-)

Closing.

---Alex
