### ISSUE TITLE
Redzone? Where is it? 

### ISSUE THREAD

**Issue by laufgas** [Alexqw/xbmc-gamepass#418]
Hi, 

I am unable to locate the redzone channel in the kodi addon. 

I can only see live nfl network and the games. Where is it? 

Thanks

**Comment by Ghoschdi** [comment]
You can only see redzone shortly before and during it being aired. You will find it right next to NFL network live about 10 minutes before air time :)

**Comment by Displayel** [comment]
what is the status for Kodi 18, will this ever be working with it ?

**Comment by aqw** [comment]
@Displayel Kodi18 support is planned, but I have zero time for the project at the moment.

In short: yes this will work with Kodi18. This project is not abandoned. But /when/ it will be ready for Kodi18, I don't know. I simply have zero time at all in my life now, which is frustrating, because pigskin is /so/ close to being ready.
