### ISSUE TITLE
"could not access game pass"

### ISSUE THREAD

**Issue by DaTroll** [Alexqw/xbmc-gamepass#49]
Hey there,

I installed your latest xbmc-gamepass-0.3.0.zip and the xmltodict you mentioned in the dependencies section. still i can't open any streams or folder views.
It seems like the xmbc addon is installed correct. when i open it in the video addon section of my xmbc it shows up at least. as soon as i want to launch it i get the "could not access game pass" error.

Im running Raspbmc with the latest stable build

any help is appreciated.

if you need further logs or information just drop me a note how to get it.

ty

DaTroll

**Comment by jamerican-284** [comment]
eriksoderblom, I have the same issue as DaTroll and have followed exactly what you have said in your post but it does not seem to work,  Do you have a step-by-step on how to get this done with the NFL Gamepass?  I went to system ... settings ...Add=ons ...enable Add-ons ...video Add-ons ... NFL Game Pass .... Configure ...Advanced ... Add-on debugging and then hit OK.  It says, "Error" : Logging into NFL Game Pass/Rewind failed.  Make sure that your account information is correct and your subscription is valid.  I would appreciate any help I can get with this.  Thanks

**Comment by eriksoderblom** [comment]
@jamerican-284 Are you sure that you have entered the correct login info in the settings?
If you have and it still doesn't work we'll need a log file to help you, we can't just guess.
The log file location depends on your system, check [this page](http://kodi.wiki/view/Log_file/Advanced#Log_files) for more info, and you will need to have Add-on debugging turned on.

**Comment by jamerican-284** [comment]
eriksoderblom, pardon me but I require a little patience since I am a newbie and very new to this whole XBMC thing.  I may require a bit of hand holding so to speak :-) .  Where do I find the log and how would I post it since the only place I access the fire stick from is from my Television set.  I do not have the Kodi on my laptop.  Thanks

**Comment by jamerican-284** [comment]
BTW eriksoderblom, the login that I enter is my email address and a password for the first time.  Is there another way of doing this?  In addition, could this have to do with the fact that the NFL Gamepass should only be accessible to IP addresses outside the United States?  I read that somewhere on this site.  Thanks

**Comment by kaileu** [comment]
You cannot use GamePass if you live in the usa.
If your IP is from inside of the US you will get an error.
For this purpose you have to use GameRewind.

Mit freundlichen Grüßen
Kai Leutner

**Comment by BaumSchorle** [comment]
@jamerican-284 do you have a paid subscribtion from GamePass or GameRewind (if you live in the us)? If you do, you need to enter your GamePass/Rewind user account to login.

**Comment by jamerican-284** [comment]
No I do not have a paid subscription to either of these.  Are you saying that although I live in the United States I can still use the service but it must be a paid subscription?  If so how do I get a paid subscription and how much does this cost?  So long as it does not cost what Direct TV charges for the NFL Sunday ticket I a, willing to pay something :-) Thanks

**Comment by BaumSchorle** [comment]
First of all, what is the difference between GamePass and GameRewind:

What is NFL Game Pass:
NFL Game Pass is website that allows those of us outside of the US (or with IPs outside of the US ;-) to watch NFL games. Archives of old games stretch back to 2009, coaches film (22 man view) is available, as is audio from each team's radio network. Overall, it is a sweet service offered by the NFL for those of us who must have our American Football fix.

What is NFL Game Rewind:
NFL Game Rewind is the USA version of Game Pass, but the service is blacked out during live games, and doesn't have access to NFL Network - Live, many of the archived shows, etc.

So since you live in the states the only option is NFL Game Rewind, to check out pricing and else visit the NFL Web-Page. As soon as you have a subscription you can use this plugin, but unlike with Direct TV you will not be able to watch live games.

**Comment by jamerican-284** [comment]
Thanks BaumSchorle.  Well that does it for me.  It is back to the drawing board for me.  I only wish that the folks showing people how to install the XBMC NFL GamePass on their Youtube video would somehow mention that it is only for folks outside the US so that folks like me would not waste time thinking that we could have access to it.  It is back to Sports Devil for me :-) ...Thanks

**Comment by Alexqw** [comment]
@jamerican-284 This plugin works for /both/ GamePass and GameRewind. Both services are provided by the NFL and require a subscription. But, each service is different (as outlined by @BaumSchorle), as the NFL has more agreements/contracts with TV networks in the US than the rest of the world.

---Alex

**Comment by jamerican-284** [comment]
Alexqw, I was told that this plugin does not work with a US IP address.  However, I hear what you are saying but the bottom line is that it is not working for me and I do not know anything about the subscription factor for US residence and how much a subscription would cost me on a monthly basis, since it is clear that  I will not be able to get it for free here in the US.

**Comment by kaileu** [comment]
Of course there are but these offers aren't legal!
The only legal way is the nfl rewind service. People try to unblock Gamepass in US with vpn or proxys but to setup these services or completly access nfl without paying is a kind of illegal usage so we can't provide you help sorry.

We can only help with a legal use of the software.

Mit freundlichen Grüßen
Kai Leutner

> Am 28.05.2015 um 15:11 schrieb jamerican-284 <notifications@github.com>:
> 
> Is there another source that is free or even for a small fee that will
> allow me to watch live NFL and NBA games in the United States via my Kodi?
> Thanks
> 
>
